stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Using Docker Compose version:"
    - docker-compose version
    - echo "Building..."
    - docker-compose build

test:
  stage: test
  image: node:16
  services:
    - docker:dind
  before_script:
    - echo "Docker Compose up..."
    - docker-compose up -d  
    - npm install           
  script:
    - echo "Running tests..."
    - npm test              
  after_script:
    - echo "Shutting down services..."
    - docker-compose down

deploy:
  stage: deploy
  script:
    - echo "Deploying..."