stages:
  - build
  - lint
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Building containers..."
    - docker-compose build

lint:
  stage: lint
  script:
    - echo "Running ESLint..."
    - npm install
    - npx eslint "**/*.js" --max-warnings=0   

test:
  stage: test
  before_script:
    - echo "Starting services..."
    - docker-compose up -d  
    - npm install           
  script:
    - echo "Running tests..."
    - npm test              
  after_script:
    - echo "Shutting down services..."
    - docker-compose down

deploy:
  stage: deploy
  script:
    - echo "Deploying application to local machine..."
    - docker-compose up -d