stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: docker/compose:latest
  script:
    - echo "Using Docker Compose version:"
    - docker-compose version
    - echo "Building..."
    - docker-compose build

test:
  stage: test
  script:
    - echo "Running tests... TODO"

deploy:
  stage: deploy
  script:
    - echo "Deploying..."