stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: docker/compose:latest
  script:
    - echo "Building..."
    - docker-compose -f docker-compose.yml build

test:
  stage: test
  image: docker/compose:latest
  script:
    - echo "Running tests... TODO"
    - docker-compose -f docker-compose.yml up -d
    - docker-compose -f docker-compose.yml down

deploy:
  stage: deploy
  image: docker/compose:latest
  script:
    - echo "Deploying..."
    - docker-compose -f docker-compose.yml down
    - docker-compose -f docker-compose.yml up -d