services:
  service1_1:
    container_name: service1_1
    build: ./service1
    expose:
      - 8199 
    depends_on:
      - service2
    networks:
      - frontend
      - backend
  service1_2:
    container_name: service1_2
    build: ./service1
    expose:
      - 8199
    depends_on:
      - service2
    networks:
      - frontend
      - backend
  service1_3:
    container_name: service1_3
    build: ./service1
    expose:
      - 8199
    depends_on:
      - service2
    networks:
      - frontend
      - backend
  service2:
    container_name: service2
    build: ./service2
    expose:
      - 8300
    networks:
      - backend

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "8081:80"
    networks:
      - frontend
    depends_on:
      - service1_1
      - service1_2
      - service1_3

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

