services:
  service1:
    build: ./service1
    expose:
      - 8199
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - service2
    deploy:
      replicas: 3
    
  service2:
    container_name: service2
    build: ./service2
    expose:
      - 8300
    networks:
      - backend

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "8081:80"
    networks:
      - frontend
      - backend
    depends_on:
      - service1
  
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

