services:
  service1_1:
    container_name: service1_1
    build: ./service1
    ports:
      - "8199" 
    depends_on:
      - service2
    networks:
      - network
  service1_2:
    container_name: service1_2
    build: ./service1
    ports:
      - "8199"
    depends_on:
      - service2
    networks:
      - network
  service1_3:
    container_name: service1_3
    build: ./service1
    ports:
      - "8199" 
    depends_on:
      - service2
    networks:
      - network
  service2:
    container_name: service2
    build: ./service2
    expose:
      - 8300
    networks:
      - network

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "8081:80"
    networks:
      - network
    depends_on:
      - service1_1
      - service1_2
      - service1_3

networks:
  network:
    driver: bridge

