
services:
  service1:
    build: ./service1
    expose:
      - 8199
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - service2
    deploy:
      replicas: 3
    
  service2:
    container_name: service2
    build: ./service2
    expose:
      - 8300
    networks:
      - backend

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "8198:80"
    networks:
      - frontend
      - backend
    depends_on:
      - service1
      - api_gateway
    volumes:
      - ./nginx_logs:/var/log/nginx  # Mount logs to host
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  api_gateway:
    container_name: api_gateway
    build: ./api_gateway
    ports:
      - "8197:8197"
    networks:
      - frontend
      - backend
    volumes:
      - ./nginx_logs:/var/log/nginx 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  nginx_logs: {}
