version: '3'
services:
  service1:
    container_name: service1
    build: ./service1
    ports:
      - "8199:8199"
    depends_on:
      - service2
    networks:
      - network
  service2:
    container_name: service2
    build: ./service2
    expose:
      - 8300
    networks:
      - network

networks:
  network:
    driver: bridge

